#!/bin/sh
# ----------------------------------------------------------------------------
#  Copyright 2001-2006 The Apache Software Foundation.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# ----------------------------------------------------------------------------

#   Copyright (c) 2001-2002 The Apache Software Foundation.  All rights
#   reserved.

BASEDIR="../galago-3.10-bin"


BASEDIR=`(cd "$BASEDIR"; pwd)`



# OS specific support.  $var _must_ be set to either true or false.
cygwin=false;
darwin=false;
case "`uname`" in
  CYGWIN*) cygwin=true ;;
  Darwin*) darwin=true
           if [ -z "$JAVA_VERSION" ] ; then
             JAVA_VERSION="CurrentJDK"
           else
             echo "Using Java version: $JAVA_VERSION"
           fi
           if [ -z "$JAVA_HOME" ] ; then
             JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/${JAVA_VERSION}/Home
           fi
           ;;
esac

if [ -z "$JAVA_HOME" ] ; then
  if [ -r /etc/gentoo-release ] ; then
    JAVA_HOME=`java-config --jre-home`
  fi
fi

# For Cygwin, ensure paths are in UNIX format before anything is touched
if $cygwin ; then
  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
  [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
fi

# If a specific java binary isn't specified search for the standard 'java' binary
if [ -z "$JAVACMD" ] ; then
  if [ -n "$JAVA_HOME"  ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
      # IBM's JDK on AIX uses strange locations for the executables
      JAVACMD="$JAVA_HOME/jre/sh/java"
    else
      JAVACMD="$JAVA_HOME/bin/java"
    fi
  else
    JAVACMD=`which java`
  fi
fi

if [ ! -x "$JAVACMD" ] ; then
  echo "Error: JAVA_HOME is not defined correctly."
  echo "  We cannot execute $JAVACMD"
  exit 1
fi

if [ -z "$REPO" ]
then
  REPO="$BASEDIR"/lib
fi

CLASSPATH=$CLASSPATH_PREFIX:"$BASEDIR"/etc:"$REPO"/tupleflow-3.10.jar:"$REPO"/trove4j-3.0.3.jar:"$REPO"/utility-3.10.jar:"$REPO"/xz-1.5.jar:"$REPO"/jsr305-3.0.0.jar:"$REPO"/jetty-server-9.3.5.v20151012.jar:"$REPO"/javax.servlet-api-3.1.0.jar:"$REPO"/jetty-http-9.3.5.v20151012.jar:"$REPO"/jetty-util-9.3.5.v20151012.jar:"$REPO"/jetty-io-9.3.5.v20151012.jar:"$REPO"/commons-compress-1.9.jar:"$REPO"/tupleflow-gridengine-3.10.jar:"$REPO"/drmaa-1.0.jar:"$REPO"/eval-3.10.jar:"$REPO"/commons-math3-3.5.jar:"$REPO"/snowball-stemmers-3.10.jar:"$REPO"/krovetz-stemmer-3.10.jar:"$REPO"/bliki-core-3.0.19.jar:"$REPO"/commons-httpclient-3.1.jar:"$REPO"/xmlenc-0.52.jar:"$REPO"/snappy-java-1.0.5-M4.jar:"$REPO"/reflections-0.9.10.jar:"$REPO"/guava-15.0.jar:"$REPO"/javassist-3.19.0-GA.jar:"$REPO"/annotations-2.0.1.jar:"$REPO"/caffeine-2.0.2.jar:"$REPO"/commons-logging-1.2.jar:"$REPO"/commons-codec-1.9.jar:"$REPO"/core-3.10.jar

MEM_SIZE_MX_KB=`free|grep Mem|awk '{print $2}'`
MEM_SIZE_MIN_KB=$((3*$MEM_SIZE_MX_KB/4))

EXTRA_JVM_ARGUMENTS="-ea -Dfile.encoding=UTF-8 -Xms${MEM_SIZE_MIN_KB}k -Xmx${MEM_SIZE_MX_KB}k -server"

# For Cygwin, switch paths to Windows format before running java
if $cygwin; then
  [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
  [ -n "$HOME" ] && HOME=`cygpath --path --windows "$HOME"`
  [ -n "$BASEDIR" ] && BASEDIR=`cygpath --path --windows "$BASEDIR"`
  [ -n "$REPO" ] && REPO=`cygpath --path --windows "$REPO"`
fi

exec "$JAVACMD" $JAVA_OPTS \
  $EXTRA_JVM_ARGUMENTS \
  -classpath "$CLASSPATH" \
  -Dapp.name="galago" \
  -Dapp.pid="$$" \
  -Dapp.repo="$REPO" \
  -Dbasedir="$BASEDIR" \
  org.lemurproject.galago.core.tools.App \
  "$@"
