FWD_INDEX_SUBDIR="forward_index"
LUCENE_INDEX_SUBDIR="lucene_index"
LUCENE_CACHE_SUBDIR="lucene_index"

EMBED_SUBDIR="embeddings"
INPUT_DATA_SUBDIR="input_data"

BITEXT_SUBDIR="bitext"
GIZA_SUBDIR="giza"
GIZA_ITER_QTY=5

METRIC_TYPE="NDCG@20"
NUM_RAND_RESTART=10

TRAIN_SUBDIR="train"

RESULTS_DIR="results"

QREL_FILE="qrels.txt"
